### PR TITLE
[chore] Pest v2 upgrade

### PR DESCRIPTION
**Pull request by fabio-ivona**

### CODE REVIEW

**Comment by mikemand** [comment]
Will you tag a new release for Pest v2, please?

**Comment by fabio-ivona** [comment]
Will be tagged soon, we are finishing the last checks

**Comment by fabio-ivona** [comment]
> Will you tag a new release for Pest v2, please?

@mikemand Released!

**Comment by mikemand** [comment]
> @mikemand Released!

Thank you!

**Pull request merged**
